RFdiffusion is running; next feed fasta into MPNN

diff --git a/tools/sequence-sampler/Dockerfile b/tools/sequence-sampler/Dockerfile
--- a/tools/sequence-sampler/Dockerfile
+++ b/tools/sequence-sampler/Dockerfile
@@ -1,18 +1,28 @@
-# Start with a base image that has CUDA and Python
-FROM rapidsai/mambaforge-cuda:cuda11.8.0-base-ubuntu22.04-py3.9
 # FROM docker.io/pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime
+FROM rapidsai/mambaforge-cuda:cuda11.8.0-base-ubuntu22.04-py3.9
 
-# Install system dependencies
-RUN apt-get update && apt-get install -y wget git nano less zip unzip && rm -rf /var/lib/apt/lists/*
+ENV DEBIAN_FRONTEND=noninteractive_autoprompt
+
+# Install required packages
+RUN apt-get update -y && \
+     apt-get install --no-install-recommends -y wget aria2 git zip unzip less nano build-essential
+
+# Install any missing CUDA libraries or tools
+RUN apt-get update && apt-get install -y --no-install-recommends \
+    cuda-libraries-11-8 \
+    cuda-nvtx-11-8 \
+    libcublas-11-8 \
+    && apt-get clean \
+    && rm -rf /var/lib/apt/lists/*
+
+# Install hydra-core
+RUN pip3 install --no-cache-dir hydra-core --upgrade pandas
 
 # Set CUDA version and ColabFold version as arguments
 ARG CUDA_VERSION=11.8.0
-ARG COLABFOLD_VERSION=1.5.3
+ARG COLABFOLD_VERSION=1.5.5
 
 WORKDIR /app
-
-ENV PYTHONUNBUFFERED=1
-ENV HYDRA_FULL_ERROR=1
 
 # Install CUDA nvcc
 RUN apt-get update && apt-get install -y cuda-nvcc-$(echo $CUDA_VERSION | cut -d'.' -f1,2 | tr '.' '-') --no-install-recommends --no-install-suggests && rm -rf /var/lib/apt/lists/*
@@ -29,6 +39,32 @@ RUN pip install -r requirements.txt
 # Additional installations
 RUN pip install hydra-core omegaconf pandas biopython pyyaml
 
+# RUN git clone https://github.com/sokrypton/RFdiffusion.git
+RUN git clone https://github.com/RosettaCommons/RFdiffusion.git
+RUN pip -q install jedi omegaconf hydra-core icecream pyrsistent
+RUN pip install dgl==1.0.2+cu116 -f https://data.dgl.ai/wheels/cu116/repo.html
+RUN cd RFdiffusion/env/SE3Transformer; pip -q install --no-cache-dir -r requirements.txt; pip -q install .
+RUN wget -qnc https://files.ipd.uw.edu/krypton/ananas
+RUN chmod +x ananas
+
+# Download params, modules and schedules
+RUN set -ex; \
+     mkdir -p params && \
+     aria2c -q -x 16 https://files.ipd.uw.edu/krypton/schedules.zip && \
+     aria2c -q -x 16 http://files.ipd.uw.edu/pub/RFdiffusion/6f5902ac237024bdd0c176cb93063dc4/Base_ckpt.pt && \
+     aria2c -q -x 16 http://files.ipd.uw.edu/pub/RFdiffusion/e29311f6f1bf1af907f9ef9f44b8328b/Complex_base_ckpt.pt && \
+     aria2c -q -x 16 https://storage.googleapis.com/alphafold/alphafold_params_2022-12-06.tar && \
+     tar -xvf alphafold_params_2022-12-06.tar -C params && \
+     rm -rf alphafold_params_2022-12-06.tar && \
+     mkdir -p RFdiffusion/models; mv Base_ckpt.pt Complex_base_ckpt.pt RFdiffusion/models/ && \
+     unzip schedules.zip; rm schedules.zip && \
+     touch params/done.txt
+
+# Install prodigy
+RUN git clone -q https://github.com/haddocking/prodigy && \
+     pip install -q prodigy/
+
+# colabfold here
 # Set environment variables
 ENV PATH /usr/local/envs/colabfold/bin:$PATH
 ENV MPLBACKEND Agg
@@ -40,32 +76,10 @@ ENV DGLBACKEND="pytorch"
 # download weights for colabfold
 RUN python -m colabfold.download
 
-# Prodigy
-RUN git clone -q https://github.com/haddocking/prodigy && \
-     pip install -q prodigy/
-
-# RFdiffusion
-RUN mkdir /app/RFdiffusion && git clone https://github.com/RosettaCommons/RFdiffusion.git /app/RFdiffusion
-
-RUN pip install -q --no-cache-dir \
-  dgl==1.0.2+cu118 -f https://data.dgl.ai/wheels/cu118/repo.html \
-  torch==2.0.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118 \
-  e3nn==0.3.3 \
-  wandb==0.12.0 \
-  pynvml==11.0.0 \
-  git+https://github.com/NVIDIA/dllogger#egg=dllogger \
-  decorator==5.1.0 \
-  hydra-core==1.3.2 \
-  pyrsistent==0.19.3 \
-  /app/RFdiffusion/env/SE3Transformer \
-  && pip install --no-cache-dir /app/RFdiffusion --no-deps
-
-RUN pip install /app/RFdiffusion/env/SE3Transformer --no-deps && pip install --no-cache-dir /app/RFdiffusion --no-deps
-
-# download weights
-RUN mkdir -p /app/models 
-RUN chmod +x /app/RFdiffusion/scripts/download_models.sh
-RUN bash -x /app/RFdiffusion/scripts/download_models.sh /app/models
+# Cleanup
+RUN apt-get clean autoclean \
+    && apt-get autoremove -y \
+    && rm -rf /var/lib/cache /var/lib/log /var/lib/apt/lists/*
 
 ## ProteinMPNN
 RUN mkdir /app/ProteinMPNN && git clone https://github.com/dauparas/ProteinMPNN /app/ProteinMPNN
@@ -73,22 +87,9 @@ RUN mkdir /app/ProteinMPNN && git clone https://github.com/dauparas/ProteinMPNN 
 # Copy in Files
 COPY . /app
 
-# Label the container
-LABEL container="seqoptim:rfdiff-mpnn"
+ENV PYTHONUNBUFFERED=1
+ENV HYDRA_FULL_ERROR=1
+
 
 # entrypoint
 ENTRYPOINT ["python", "-u", "main.py"]
-
-
-# RUN pip install -q --no-cache-dir \
-#   dgl==1.0.2+cu116 -f https://data.dgl.ai/wheels/cu116/repo.html \
-#   torch==1.12.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 \
-#   e3nn==0.3.3 \
-#   wandb==0.12.0 \
-#   pynvml==11.0.0 \
-#   git+https://github.com/NVIDIA/dllogger#egg=dllogger \
-#   decorator==5.1.0 \
-#   hydra-core==1.3.2 \
-#   pyrsistent==0.19.3 \
-#   /app/RFdiffusion/env/SE3Transformer \
-#   && pip install --no-cache-dir /app/RFdiffusion --no-deps
