make public test also use gateway

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -211,6 +211,7 @@ jobs:
           docker compose ps
 
       - name: Run Equibind
+        if: matrix.bacalhau_version == '1.0.3'
         run: |
           # Add execute permission
           chmod +x plex
@@ -225,21 +226,46 @@ jobs:
             find . -name '*docked.sdf' | grep 'docked.sdf'
           fi
 
-      - name: Run docker compose logs
-        # run always even when
-        if: always()
-        run: |
-          docker compose logs
-
       - name: Run bacalhau describe
+        if: matrix.bacalhau_version == '1.0.3'
         # run always even when
-        if: always()
         run: |
           # Execute permission
           chmod +x ./bacalhau
           ./bacalhau version
           JOB_ID=$(./bacalhau list --output json | jq -r '.[0].State.JobID')
           ./bacalhau describe ${JOB_ID}
+
+      - name: Run Gateway Integration Tests
+        if: matrix.bacalhau_version == '1.1.0'
+        run: |
+          # Test Health check
+          response=$(curl --silent http://localhost:8080/healthcheck)
+          if [[ "$response" != "Healthy" ]]; then
+            echo "Test 1 failed: Expected 'Healthy' but got '$response'"
+            exit 1
+          else
+            echo "Gateway Healthcheck passed"
+          fi
+
+          # Test for File Upload
+          response=$(curl --silent -X POST \
+                          -F "file=@testdata/binding/abl/7n9g.pdb;filename=7n9g.pdb" \
+                          -F "filename=7n9g.pdb" \
+                          -F "wallet_address=0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045" \
+                          http://localhost:8080/datafiles)
+          if echo "$response" | jq -e '.cid' > /dev/null; then
+            echo "File upload test passed"
+          else
+            echo "File upload test failed: 'cid' key not found in the response"
+            exit 1
+          fi
+
+      - name: Run docker compose logs
+        # run always even when
+        if: always()
+        run: |
+          docker compose logs
 
       - name: upload outputs
         # run always even when
