update ci to test gateway instead of cli for 1.1.0

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -339,6 +339,7 @@ jobs:
           docker compose ps
 
       - name: Run Equibind
+        if: matrix.bacalhau_version == '1.0.3'
         run: |
           set -x
           # Add execute permission
@@ -369,13 +370,8 @@ jobs:
             find . -name '*docked.sdf' | grep 'docked.sdf'
           fi
 
-      - name: Run docker compose logs
-        # run always even when
-        if: always()
-        run: |
-          docker compose logs
-
       - name: Run bacalhau describe
+        if: matrix.bacalhau_version == '1.0.3'
         # run always even when
         if: always()
         run: |
@@ -384,6 +380,23 @@ jobs:
           ./bacalhau version
           JOB_ID=$(./bacalhau list --output json | jq -r '.[0].State.JobID')
           ./bacalhau describe ${JOB_ID}
+
+    -name: Run Gateway Integration Tests
+        if: matrix.bacalhau_version == '1.1.0'
+        run |
+          response=$(curl --silent http://localhost:8080/healthcheck)
+          if [[ "$response" != "Healthy" ]]; then
+            echo "Test 1 failed: Expected 'Healthy' but got '$response'"
+            exit 1
+          else
+            echo "Gateway Healthcheck passed"
+          fi
+
+      - name: Run docker compose logs
+        # run always even when
+        if: always()
+        run: |
+          docker compose logs
 
       - name: upload outputs
         # run always even when
